[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["."]
markers = [
    "anyio(name): mark тестов, требующих выполнения на указанном AnyIO-бэкенде",
]
